### PR TITLE
Molchanoviv nested forms example

### PR DESCRIPTION
**Pull request by phiamo**
this extends #41 for a menu template and controller action...

### CODE REVIEW

**Comment by molchanoviv** [comment]
@phiamo Can you please describe in details what is wrong with replacement?

**Comment by phiamo** [comment]
bildschirmfoto von 2015-04-28 10 52 18
you see the name / label thing, i think we need to improve the example further

**Comment by phiamo** [comment]
bildschirmfoto von 2015-04-28 11 03 04
ok i improved this

**Comment by phiamo** [comment]
humm probably i should have dumped assetic etc while in dev on prod this works even better
http://bootstrap.mohrenweiserpartner.de/mopa/bootstrap/forms/collections/nested

**Comment by molchanoviv** [comment]
super :+1:

**Pull request merged**
